### ISSUE TITLE
Расположение файлов

### ISSUE THREAD

**Issue by RomkaZVO** [Otorhin/DDLC-Rus-Android#1]
Необходимо перенести файлы по пути android/data/package.name
По двум причинам
1) Обычноюзеры не удалят Монику.
2) Не всем может хватить место в /data.

**Comment by Otorhin** [comment]
Кхм. Они как-бы и так там =]. Если же нет, то очень странно. У моей команды тестеров все было в Android/Data

**Comment by Otorhin** [comment]
Хм... Опять таки. Привлек людей. Android 5.0, Android 6.0, Android 7.0. Создает в android/data

**Comment by Otorhin** [comment]
Сами скрипты, картинки в апк хранятся. Для чего они будут дважды занимать место в памяти устройства?

**Comment by RomkaZVO** [comment]
Так это плохо. Не у всех оно может установиться

**Comment by Otorhin** [comment]
Ты имеешь большой вид APK? Или как?

**Comment by RomkaZVO** [comment]
Оно самое, большой апк съест больше места с /data. Да и не у всех там есть должное количество места.

**Comment by Otorhin** [comment]
Пересоберу с кэшом сегодня. С фиксом GUI. А вообще не думаю что обсуждение APK относиться к самим скриптам =]

**Comment by RomkaZVO** [comment]
Отличненько)

**Comment by Otorhin** [comment]
Так. А что у тебя было что они в data/data создавались?

**Comment by RomkaZVO** [comment]
![screenshot_20180105-225640](https://user-images.githubusercontent.com/15728269/34614246-bd998e1e-f26b-11e7-955a-6f79ab966b82.png)
Да я на это отреагировал

**Comment by Otorhin** [comment]
Хех. На либы RenPy. Ладно. Я закрыл. Нужно открыть писать на me@otorhin.xyz
