### ISSUE TITLE
Кнопка вне textbox

### ISSUE THREAD

**Issue by RomkaZVO** [Otorhin/DDLC-Rus-Android#2]
Все собсна на скрине.
![screenshot_20180105-212203](https://user-images.githubusercontent.com/15728269/34610977-85da239c-f25e-11e7-8029-93726de38aef.png)

**Comment by Otorhin** [comment]
Хорошо. Запишу. Просто мы не особо ими пользовались =]

**Comment by RomkaZVO** [comment]
![screenshot_20180105-223520](https://user-images.githubusercontent.com/15728269/34613447-d50b20d8-f268-11e7-8d2c-8fd0d281fa76.png)Сохранился и получил эти файлы? Но где все остальное?

**Comment by RomkaZVO** [comment]
Пишу сюда, ибо не могу в ту исусю писать

**Comment by Otorhin** [comment]
Так. Ту я вроде открыл =\. А вообще какие другие? Там максимум еще четыре файла по мере прохождения. Изначально firstrun и чартеры

**Comment by RomkaZVO** [comment]
Я про все остальные файлы скрипты, картинки и прочее.

**Comment by RomkaZVO** [comment]
![default](https://user-images.githubusercontent.com/15728269/34613696-9f030fae-f269-11e7-8029-2710e9559771.PNG)

**Comment by Otorhin** [comment]
Переходи туда

**Comment by Otorhin** [comment]
Ну. Я пофиксил. Сейчас закину правленные скрипты и добавлю новую сборку в readme
